[project]
name = "FresherScout Scheduler"
version = 0.1
dependencies = [
  "airflow >=2.10.5"
]
requires-python = ">=3.11"
authors = [ 
  { name = "Pawel Jancewicz", email="jancewicz.pawel1@gmail.com" } 
  ]
description = "Scheduler to run FresherScout once a day" 